spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/cryptocurrencywatcher
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

app:
  percentForComparison: 0.01
  requestTimeoutInSec: 5
  parallelism: 3
  host: "https://api.coinlore.net/api/ticker/?id="
  coinsId:
    - 90
    - 48543
    - 80



